"""Hardware-independent game rules."""

from .bowling import (
    BowlingGame,
    BowlingSnapshot,
    FrameSnapshot,
    IllegalRollError,
    RollSnapshot,
)
from .cumulative import (
    CumulativeFrameSnapshot,
    CumulativeGame,
    CumulativeRollSnapshot,
    CumulativeSnapshot,
    IllegalCumulativeRollError,
    InvalidCumulativeConfigurationError,
)
from .match import (
    BowlingMatch,
    InvalidMatchConfigurationError,
    MatchCompleteError,
    MatchRollResult,
    MatchSnapshot,
    PlayerColor,
    PlayerSnapshot,
    StandingSnapshot,
)
from .cumulative_match import (
    CumulativeMatch,
    CumulativeMatchCompleteError,
    CumulativeMatchPlayerSnapshot,
    CumulativeMatchRollResult,
    CumulativeMatchSnapshot,
    CumulativeStandingSnapshot,
    InvalidCumulativeMatchConfigurationError,
)
from .config import (
    BrandingSnapshot,
    ControlStyle,
    InvalidMatchConfigError,
    LOCKED_BRANDING,
    MatchConfig,
    Mode,
    Theme,
)
from .throw_controls import (
    CurveLevel, InvalidThrowControlError, PowerFeedback, ThrowControlCommand,
    ThrowControlCommandKind, ThrowControlMachine, ThrowControlOutcome,
    ThrowControlOutcomeKind, ThrowControlPhase, ThrowControlSnapshot, ThrowSetup,
)
from .schedule import (
    InvalidScheduleConfigurationError,
    PartyFrameSchedule,
    PartySchedule,
    PartySetupDefinition,
    RemixFrameSchedule,
    RemixObject,
    RemixSchedule,
    ScheduleModeError,
    build_party_schedule,
    build_remix_schedule,
)

__all__ = [
    "BowlingGame",
    "BowlingSnapshot",
    "FrameSnapshot",
    "IllegalRollError",
    "RollSnapshot",
    "CumulativeFrameSnapshot",
    "CumulativeGame",
    "CumulativeRollSnapshot",
    "CumulativeSnapshot",
    "IllegalCumulativeRollError",
    "InvalidCumulativeConfigurationError",
    "BowlingMatch",
    "InvalidMatchConfigurationError",
    "MatchCompleteError",
    "MatchRollResult",
    "MatchSnapshot",
    "PlayerColor",
    "PlayerSnapshot",
    "StandingSnapshot",
    "CumulativeMatch",
    "CumulativeMatchCompleteError",
    "CumulativeMatchPlayerSnapshot",
    "CumulativeMatchRollResult",
    "CumulativeMatchSnapshot",
    "CumulativeStandingSnapshot",
    "InvalidCumulativeMatchConfigurationError",
    "BrandingSnapshot",
    "ControlStyle",
    "InvalidThrowControlError",
    "CurveLevel",
    "PowerFeedback",
    "ThrowControlPhase",
    "ThrowControlCommandKind",
    "ThrowControlCommand",
    "ThrowSetup",
    "ThrowControlOutcomeKind",
    "ThrowControlOutcome",
    "ThrowControlSnapshot",
    "ThrowControlMachine",
    "InvalidMatchConfigError",
    "LOCKED_BRANDING",
    "MatchConfig",
    "Mode",
    "Theme",
    "InvalidScheduleConfigurationError",
    "PartyFrameSchedule",
    "PartySchedule",
    "PartySetupDefinition",
    "RemixFrameSchedule",
    "RemixObject",
    "RemixSchedule",
    "ScheduleModeError",
    "build_party_schedule",
    "build_remix_schedule",
]
