"""Hardware-independent game rules."""

from .bowling import (
    BowlingGame,
    BowlingSnapshot,
    FrameSnapshot,
    IllegalRollError,
    RollSnapshot,
)
from .bowling_round import (
    InvalidBowlingRoundValueError, BowlingThrowNumber, BowlingThrowResultKind,
    BowlingThrowResult, BowlingRoundSnapshot, BowlingRoundMachine,
)
from .player_darts import (
    InvalidPlayerDartValueError, PlayerColor, player_color_for_number,
    emulator_dart_color, emulator_dart_indices_for_color,
    emulator_dart_indices_for_player, is_emulator_dart_for_player,
)
from .cumulative import (
    CumulativeFrameSnapshot,
    CumulativeGame,
    CumulativeRollSnapshot,
    CumulativeSnapshot,
    IllegalCumulativeRollError,
    InvalidCumulativeConfigurationError,
)
from .match import (
    BowlingMatch,
    InvalidMatchConfigurationError,
    MatchCompleteError,
    MatchRollResult,
    MatchSnapshot,
    PlayerSnapshot,
    StandingSnapshot,
)
from .cumulative_match import (
    CumulativeMatch,
    CumulativeMatchCompleteError,
    CumulativeMatchPlayerSnapshot,
    CumulativeMatchRollResult,
    CumulativeMatchSnapshot,
    CumulativeStandingSnapshot,
    InvalidCumulativeMatchConfigurationError,
)
from .config import (
    BrandingSnapshot,
    ControlStyle,
    InvalidMatchConfigError,
    LOCKED_BRANDING,
    MatchConfig,
    Mode,
    Theme,
)
from .throw_controls import (
    CurveLevel, InvalidThrowControlError, PowerFeedback, ThrowControlCommand,
    ThrowControlCommandKind, ThrowControlMachine, ThrowControlOutcome,
    ThrowControlOutcomeKind, ThrowControlPhase, ThrowControlSnapshot, ThrowSetup,
    THROW_FOUL_SECONDS, THROW_WARNING_SECONDS,
)
from .ball_trajectory import (
    BALL_RADIUS_PIXELS, BALL_START_X, BALL_START_Y, BALL_MIN_X, BALL_MAX_X,
    BALL_MIN_Y, BALL_MAX_Y, MAX_CURVE_OFFSET_PIXELS,
    InvalidBallTrajectoryValueError, BallTrajectory, BallTrajectorySample,
    build_ball_trajectory, sample_ball_trajectory, sample_ball_trajectory_progress,
    ball_trajectory_point_at_progress, ball_trajectory_derivative_at_progress,
)
from .pinfall import (InvalidPinfallValueError, PinImpactBias, PinfallResolution,
    PIN_RADIUS_PIXELS, BALL_PIN_CONTACT_RADIUS_PIXELS, COLLISION_SUBDIVISIONS,
    PINFALL_DURATION_SECONDS, PINFALL_WAVE_DELAY_SECONDS, PINFALL_PIN_DURATION_SECONDS,
    PIN_CENTERS, PIN_CHILDREN, resolve_ball_pinfall, sample_ball_roll)
from .schedule import (
    InvalidScheduleConfigurationError,
    PartyFrameSchedule,
    PartySchedule,
    PartySetupDefinition,
    RemixFrameSchedule,
    RemixObject,
    RemixSchedule,
    ScheduleModeError,
    build_party_schedule,
    build_remix_schedule,
)

__all__ = [
    "InvalidBowlingRoundValueError", "BowlingThrowNumber", "BowlingThrowResultKind",
    "BowlingThrowResult", "BowlingRoundSnapshot", "BowlingRoundMachine",
    "InvalidPlayerDartValueError", "player_color_for_number", "emulator_dart_color",
    "emulator_dart_indices_for_color", "emulator_dart_indices_for_player",
    "is_emulator_dart_for_player",
    "BowlingGame",
    "BowlingSnapshot",
    "FrameSnapshot",
    "IllegalRollError",
    "RollSnapshot",
    "CumulativeFrameSnapshot",
    "CumulativeGame",
    "CumulativeRollSnapshot",
    "CumulativeSnapshot",
    "IllegalCumulativeRollError",
    "InvalidCumulativeConfigurationError",
    "BowlingMatch",
    "InvalidMatchConfigurationError",
    "MatchCompleteError",
    "MatchRollResult",
    "MatchSnapshot",
    "PlayerColor",
    "PlayerSnapshot",
    "StandingSnapshot",
    "CumulativeMatch",
    "CumulativeMatchCompleteError",
    "CumulativeMatchPlayerSnapshot",
    "CumulativeMatchRollResult",
    "CumulativeMatchSnapshot",
    "CumulativeStandingSnapshot",
    "InvalidCumulativeMatchConfigurationError",
    "BrandingSnapshot",
    "ControlStyle",
    "InvalidThrowControlError",
    "CurveLevel",
    "PowerFeedback",
    "ThrowControlPhase",
    "ThrowControlCommandKind",
    "ThrowControlCommand",
    "ThrowSetup",
    "ThrowControlOutcomeKind",
    "ThrowControlOutcome",
    "ThrowControlSnapshot",
    "ThrowControlMachine",
    "THROW_WARNING_SECONDS",
    "THROW_FOUL_SECONDS",
    "BALL_RADIUS_PIXELS", "BALL_START_X", "BALL_START_Y", "BALL_MIN_X",
    "BALL_MAX_X", "BALL_MIN_Y", "BALL_MAX_Y", "MAX_CURVE_OFFSET_PIXELS",
    "InvalidBallTrajectoryValueError", "BallTrajectory", "BallTrajectorySample",
    "build_ball_trajectory", "sample_ball_trajectory", "sample_ball_trajectory_progress",
    "ball_trajectory_point_at_progress", "ball_trajectory_derivative_at_progress",
    "InvalidPinfallValueError", "PinImpactBias", "PinfallResolution", "PIN_RADIUS_PIXELS", "BALL_PIN_CONTACT_RADIUS_PIXELS", "COLLISION_SUBDIVISIONS", "PINFALL_DURATION_SECONDS", "PINFALL_WAVE_DELAY_SECONDS", "PINFALL_PIN_DURATION_SECONDS", "PIN_CENTERS", "PIN_CHILDREN", "resolve_ball_pinfall", "sample_ball_roll",
    "InvalidMatchConfigError",
    "LOCKED_BRANDING",
    "MatchConfig",
    "Mode",
    "Theme",
    "InvalidScheduleConfigurationError",
    "PartyFrameSchedule",
    "PartySchedule",
    "PartySetupDefinition",
    "RemixFrameSchedule",
    "RemixObject",
    "RemixSchedule",
    "ScheduleModeError",
    "build_party_schedule",
    "build_remix_schedule",
]
